###login
GET http://localhost:8764/login?user=Pium&password=123
Accept: application/json
Content-Type: application/json

> {%
    client.global.set("token", response.body.accessToken);
    client.global.set("refresh", response.body.refreshToken);
%}

###refresh token
GET http://localhost:8764/refreshToken?refreshToken={{refresh}}
Accept: application/json
Content-Type: application/json

> {%
    client.global.set("token", response.body.accessToken);;
%}

###register
POST http://localhost:8764/credentials
Accept: application/json
Content-Type: application/json

{
  "username": "Prueba",
"password": "123"
}


###get all clientes
GRAPHQL {{host}}
Authorization: Bearer {{token}}

query GetCliente {
    getClientes {
        id
        nombre
        email
    }
}

###get all empleados
GRAPHQL {{host}}
Authorization: Bearer {{token}}

query GetEmpleadosByIdTienda($id: ID!) {
    getEmpleadosByIdTienda(id: $id) {
        id
        nombre
        apellido
        cargo
    }
}

{
      "id": 1
}

###get all productos
GRAPHQL {{host}}
Authorization: Bearer {{token}}

query GetProductos {
    getProductos {
        id
        nombre
        precio
    }
}

###Get all ventas
GRAPHQL {{host}}
Authorization: Bearer {{token}}

query GetVentas {
    getVentas {
        id
        fecha
        total
    }
}

###delete cliente
GRAPHQL {{host}}
Authorization: Bearer {{token}}

mutation DeleteCliente($id: ID!) {
    deleteCliente(id: $id)
}
{
    "id": 1000
}



###update venta
GRAPHQL {{host}}
Authorization: Bearer {{token}}

mutation UpdateVenta($updateVentaInput: UpdateVentaInput!) {
    updateVenta(updateVentaInput: $updateVentaInput)
}
{
  "updateVentaInput": {
    "id": 8,
    "fecha": "2021-10-10",
    "total": 1200,
    "clienteId": 2,
    "empleadoId": 1
  }
}

###add empleado
GRAPHQL {{host}}
Authorization: Bearer {{token}}

mutation AddEmpleado($empleadoInput: EmpleadoInput!) {
    addEmpleado(empleadoInput: $empleadoInput)
}
{
  "empleadoInput": {
    "apellido": "Novillo",
    "nombre": "Oscar",
    "cargo": "El Aprobador",
    "tiendaId": 1
  }
}

###get venta by id
GRAPHQL {{host}}
Authorization: Bearer {{token}}

query GetVentaById($id: ID!) {
    getVentaById(id: $id) {
        id
        fecha
        total
        clienteId
        empleadoId
    }
}
{
    "id": 1
}